services:
  app:
    image: php:8.1-fpm
    container_name: php-app
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./vendor:/var/www/vendor
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USERNAME: username
      DB_PASSWORD: password
    command: >
      /bin/sh -c "apt-get update &&
                  apt-get install -y libpq-dev &&
                  docker-php-ext-install pdo pdo_pgsql &&
                  php-fpm"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
